### ISSUE TITLE
Search page image if missing

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#1]
**Steps:**
The url: https://107soyodhyqw1pzu-59207385288.shopifypreview.com/search?q=t&options%5Bprefix%5D=last
Click on the url.

**Actual result:** 
The image is missing for the search page.
![image](https://user-images.githubusercontent.com/102131636/161686453-e4c69e39-eee2-44f1-9798-718feef5c2f0.png)

**Expected result:** 
All products have the image.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  updated

**Comment by sudhanshu0603** [comment]
ok, resolved
