### ISSUE TITLE
The spelling mistakes for cookies in the home page category

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#11]
**Actual result:**
The spelling is not correct for the cookies in the home page.
![image](https://user-images.githubusercontent.com/102131636/161698172-9656b9ee-b9d5-4624-a8cb-834cd53340ea.png)

**Expected result:**
The spelling have to be correct.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  Resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
