### ISSUE TITLE
In collection page the images are not added.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#12]
**The url :** https://107soyodhyqw1pzu-59207385288.shopifypreview.com/collections
**Actual result :**
The images are missing for the collection page.
![image](https://user-images.githubusercontent.com/102131636/161699284-46657d75-e47c-4ec9-8a54-4f0ffe54f77c.png)

**Expected result:** 
The images have to be added.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  this is not an issue, there is neither any product in that collection nor collection image are there, if either product or collection image will upload, it will run properly then

**Comment by sudhanshu0603** [comment]
is it possible to disabled the product which do not exist and once the product will be import  then the it will appears. 
@dev-adityapatel .

**Comment by sudhanshu0603** [comment]
ok, resolved
