### ISSUE TITLE
All collection links the image of the product is not added.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#13]
**The url:**  https://107soyodhyqw1pzu-59207385288.shopifypreview.com/collections/all

**Actual result:**
The image is missing .
![image](https://user-images.githubusercontent.com/102131636/161699753-6e4c7ac8-c590-4828-ab4e-46a43acc637b.png)

**Expected result:**
The image have to be added.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  Actually this an exception case, in this this product neither product image uploaded properly nor any variant uploaded carefully, for now, I set to draft that particular product

**Comment by sudhanshu0603** [comment]
ok, resolved
