### ISSUE TITLE
The different language is coming 

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#14]
The url: https://107soyodhyqw1pzu-59207385288.shopifypreview.com/pages/how-to-shop

**Actual result:**
The content is coming of different language.
![image](https://user-images.githubusercontent.com/102131636/161701463-50a7736a-16d5-4730-a757-5862bb189f8c.png)

**Expected result:**
The content have to be in english language

**Comment by dev-adityapatel** [comment]
![image](https://user-images.githubusercontent.com/100192519/161984871-b5f06e30-a918-4ce1-bff0-b4300bf82ee7.png)

@sudhanshu0603  Updated

**Comment by sudhanshu0603** [comment]
ok, @dev-adityapatel , once we get the content  i will close the this issue.

**Comment by sudhanshu0603** [comment]
ok ,resolved
