### ISSUE TITLE
The page of refund policy need to be Returns and Refund Policy it will be much better and the url have to be also change for it.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#16]
The url : https://107soyodhyqw1pzu-59207385288.shopifypreview.com/pages/refund-policy
**Actual result:**
1: The url is coming of refund policy only.
2: The title of the policy is only of Refund poilicy.
![image](https://user-images.githubusercontent.com/102131636/161704796-3ba07b02-8cd8-462c-9ec7-85cc39a8c344.png)

**Expected result:** 
1: The url have to be returns and refund policy.
2: The title of policy should be Returns and Refund Policy.

--------------------------------------------------------------------------------------------------------------------------------------

**RETESTING:**
Actual result: 
The title is coming Refund and Refund policy.
![image](https://user-images.githubusercontent.com/102131636/162121713-ee86528f-c74a-4c3f-b0c7-02f53773349f.png)

Expected result: Return & Refund Policy. it will be much better.
-----------------------------------------------------------------------------------------------------------------------------------
**Again retesting:**
**Actual result:**
The title on return & refund policy the word return is in singular.
The url:  https://sugarlessbliss.com/pages/return-and-refund-policy 
**Expected result:** 
1: The url have to be change i should be like returns and refund policy.
2: The work inside the form have to be Returns and Refund Policy it is coming , like Return and Refund Policy

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  Updated

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
