### ISSUE TITLE
The spelling of Policy is coming different for all policy in footer

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#17]
**Actual result :**
The spelling of Policy is coming different for all policy in footer
![image](https://user-images.githubusercontent.com/102131636/161705244-df4815f8-ed4a-4d40-9402-b129b07b1817.png)
**Expected result:** 
The spelling of Policy have to be same for all the policy pages in the footer.

**Comment by dev-adityapatel** [comment]
![image](https://user-images.githubusercontent.com/100192519/161980787-d4445898-936b-4a22-80c1-9dbbe2edde42.png)
@sudhanshu0603  Issue resolved

**Comment by sudhanshu0603** [comment]
@dev-adityapatel , the Billing Terms & Conditions policy word is in lower case,  It should be like Policy.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  Resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
