### ISSUE TITLE
The uppercase sentences in privacy policy page have to be removed. 

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#18]
The url :https://107soyodhyqw1pzu-59207385288.shopifypreview.com/pages/privacy-policy

**Actual result:** 
The uppercase sentences needs to be removed which are not related to the store.
The video issue: https://www.awesomescreenshot.com/video/8238310?key=d397d1f804884396f56e355d2505cee4

**Expected result:**
The uppercase sentences needs to be removed.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603   No need, this is default template, provided by shopify, if client provide then it will replace

**Comment by sudhanshu0603** [comment]
ok, resolved
