### ISSUE TITLE
TERMS and condition page in the footer 3 type of font are used for the text content.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#19]
The url: https://107soyodhyqw1pzu-59207385288.shopifypreview.com/pages/terms-conditions
**Actual result:** 
The font used for this page is having 3 types of font used.
![image](https://user-images.githubusercontent.com/102131636/161706897-4d35dcb0-624d-413d-a5d0-67fefd5b4b40.png)

**Expected result:**
The font of the text have to same as we have used for other policy pages.

**Comment by ui-chandrashekhar** [comment]
this is content part.
This content was put like this, I can't do anything in it

**Comment by ui-chandrashekhar** [comment]
this is content part.
This content was put like this, I can't do anything in it

**Comment by sudhanshu0603** [comment]
ok, @ui-chandrashekhar
