### ISSUE TITLE
The product image is missing in the collection page.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#2]
The url: https://107soyodhyqw1pzu-59207385288.shopifypreview.com/collections/packaging-accessories

**Actual result:** 
The image is missing for the product.
![image](https://user-images.githubusercontent.com/102131636/161688802-906b02ca-44ef-466d-871a-5a7ce84ade29.png)

**Expected result:**
The product image have to be added.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603   resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
