### ISSUE TITLE
The addtocart and title in product page is coming very close with each other.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#20]
**Actual result:** 
The title and the addto cart icon on hove over the product then they both are coming very close to each other.
![image](https://user-images.githubusercontent.com/102131636/161708572-769cef82-2e34-4800-b8e4-b9ef59f25441.png)

**Expected result:**
When we hover over the product then there should be a some space between the title and addtocart icon on product page.

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
