### ISSUE TITLE
The image of the product in the cart page is not clickable

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#21]
**Actual result:** 
The image of the product in the cart page is not clickable
![image](https://user-images.githubusercontent.com/102131636/161709675-10891809-818a-4fed-a998-22ae4b6bc27f.png)

**Expected result:**
The image of the product have to be clickable.

**Comment by dev-adityapatel** [comment]
![image](https://user-images.githubusercontent.com/100192519/161979013-536a205f-0f12-4d67-82df-1b39e8908d62.png)
Issue resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
