### ISSUE TITLE
The header icon are not of equal size.( cart, wishlist, login )

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#22]
**Actual result:** 
The header icons are not of equal size.
![image](https://user-images.githubusercontent.com/102131636/161901414-4753689e-f911-4da2-a04b-15e2d6b1b048.png)

**Expected result:**
The size of the icons have to be same in the header.

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
