### ISSUE TITLE
Collection pages banners are cropping 

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#23]
**Actual result:** 
The collection page banners are cropping.
![image](https://user-images.githubusercontent.com/102131636/161902244-1b8903f0-df72-4739-8773-a1ecda521be2.png)

**Expected result:**
The collection page banner should not break.

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
