### ISSUE TITLE
The review needs to be removed which we have added in the product.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#24]
The url: https://sugarlessbliss.com/products/sugar-free-egg-less-vanilla-sponge-cake-mix 
**Actual result:** 
The review needs to be removed which we have added in the product.
![image](https://user-images.githubusercontent.com/102131636/161903415-fdaea3da-3ab4-4bef-9045-f26787d58369.png)

**Expected result:**
The review needs to be removed.

**Comment by dev-adityapatel** [comment]
![image](https://user-images.githubusercontent.com/100192519/161971699-e69c135b-7630-4833-ae4d-0962307d3cba.png)
@sudhanshu0603  Isssue resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
