### ISSUE TITLE
The breedcrumbs full name is not coming in the product page.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#25]
The url: https://sugarlessbliss.com/products/sugar-free-egg-less-vanilla-sponge-cake-mix
**Actual result:** 
The breedcrumbs full name is not coming 
![image](https://user-images.githubusercontent.com/102131636/161903922-2b3a924c-49f7-45c5-8124-a62db15df5df.png)
**Expected result:**
The breedcrumbs have to be visible properly.

**Comment by dev-adityapatel** [comment]
![image](https://user-images.githubusercontent.com/100192519/161971183-a44a8c9e-9f64-4771-b7a4-5201ebf954a7.png)

Issue resolved

**Comment by sudhanshu0603** [comment]
ok,
