### ISSUE TITLE
You may also like section below the product page main image when we hover over the product of you may also like then the wishlist icon is not coming.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#26]
**The url:** 
https://sugarlessbliss.com/products/sugar-free-egg-less-vanilla-sponge-cake-mix
**Actual result:**
You may also like section below the product page main image when we hover over the product of you may also like then the wishlist icon is not coming.
![image](https://user-images.githubusercontent.com/102131636/161904331-980ae5d6-a941-4c45-a873-833b6c522abc.png)

**Expected result:**
When we hover over the products of you may also like section then the wishlist icon have to come on hover.

**Comment by dev-adityapatel** [comment]
Working fine

**Comment by sudhanshu0603** [comment]
ok, resolved
