### ISSUE TITLE
In quick view when we add the medium option and click on the addtocart then the red color message is coming then when we click on the small option then the error message is coming of red color but initially then we click on the small and click on addtocart then the black color message is coming

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#29]
**Actual result:**
The color combination of message is coming red as when we clicking on the add to cart.
![image](https://user-images.githubusercontent.com/102131636/161907408-36b8f09e-3eb2-424b-8812-bea259c3f34a.png)

**Expected result:**
The color of message have to be green it will be much better
--------------------------------------------------------------------------------------------------------------------------------------

**RETESTING:** 
**Actual result:** 
**The video is attached:** 
https://www.awesomescreenshot.com/video/8279114?key=a89afd7c13d0e0a4fe0467a3e648fb89
Expected result: The colour of the  message when we are adding sold out then we add the addtocart then error message have to be of green colour it will be much better
-----------------------------------------------------------------------------------------------------------------------------------------
**Again retesting:**
**Actual result:**
When cart is empty and when we addtocart the product inside the quick view then the count is not increasing in the header.
**The video is attached:** 
https://www.awesomescreenshot.com/video/8401032?key=5032b834ef652b3fc38b025fda0cdd4e
**Expected result:**
The we addtocart any product then the count have to be increased on the header using quick view

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by ui-chandrashekhar** [comment]
discussion needed @dev-adityapatel @sudhanshu0603

**Comment by ui-chandrashekhar** [comment]
@dev-adityapatel as discussed in today meeting please do needfull

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  Resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
