### ISSUE TITLE
Search page (  when we click on the input field then the wishlist is coming over the suggestion list)

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#3]
**The url:**  https://107soyodhyqw1pzu-59207385288.shopifypreview.com/search?q=t&options%5Bprefix%5D=last

**Actual result:**
The wishlist is coming over the suggestion list.
![image](https://user-images.githubusercontent.com/102131636/161690271-60e7ca6f-1316-4bfc-95c4-422ad27940c3.png)

**Expected result:**
The wishlist should come behind the suggestion list.

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
