### ISSUE TITLE
The addTocart button is coming in 2 line it have to come in single line and have some background it will be much better

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#30]
**Actual resul:**
The addTocart button is coming in 2 line it have to come in single line and have some background it will be much better
![image](https://user-images.githubusercontent.com/102131636/161910406-0b37196e-318a-411e-beaa-6e810c530633.png)
**Expected result:**
Addtocart button and the have to come in single line and have some background colour, it will be much better

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
