### ISSUE TITLE
Collection page banners are not made for the mobile view, the cropped banners are coming.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#31]
The url : https://sugarlessbliss.com/collections/dark-chocolites
**Actual result:** 
Collection page banners are not made for the mobile view, the cropped banners are coming.
![image](https://user-images.githubusercontent.com/102131636/161911712-213e2520-accb-4d2d-b0a9-25b4d2739628.png)

**Expected result:**
The collection page banners we  can add for the mobile view.
------------------------------------------------------------------------------------------------------------------------------------
**RETESTING:**
**Actual result:**
The breedcrumbs text is not visible properly.
![image](https://user-images.githubusercontent.com/102131636/162126032-4527924d-eea7-47c5-9b7f-f4a8e6b4d47c.png)

**Expected result:**
The text of breedcrumbs have to be visible properly.

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by ui-chandrashekhar** [comment]
@dev-adityapatel @sudhanshu0603

**Comment by ui-chandrashekhar** [comment]
@dev-adityapatel plese add dot after some text if still having any issues please let me know

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by sudhanshu0603** [comment]
ok ,resolved
