### ISSUE TITLE
When we click on the service section of the ( Customer Support 24 x7  ) then it is opening the home page but it can be linked to the page related to it.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#32]
**Actual result:**
When we click on the service section of the ( Customer Support 24 x7  ) then it is opening the home page but it can be linked to the page related to it.
![image](https://user-images.githubusercontent.com/102131636/161912924-b2f2c8e2-2f1a-4cd8-b443-19a631ec65cc.png)

**Expected result:**
It have to open the page related to it.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  Issue resolved

**Comment by sudhanshu0603** [comment]
@dev-adityapatel , it is not linked with any of the page, need discussion

**Comment by sudhanshu0603** [comment]
ok , resolved
