### ISSUE TITLE
The icon of the header are not of equal size in mobile view.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#33]
**Actual result:** The icon of the header are not of equal size in mobile view.
![image](https://user-images.githubusercontent.com/102131636/161913676-578d920a-03fb-4beb-9d5d-289f03f2824e.png)
**Expected result:**
The icon of the header have to be of equal size it will be much better.

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
