### ISSUE TITLE
When we click on the hambergur and scroll down the page then the empty space is coming below social media icon inside the hambergur.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#34]
**Actual result:**
When we click on the hambergur and scroll down the page then the empty space is coming below social media icon inside the hambergur.
![image](https://user-images.githubusercontent.com/102131636/161922522-636db184-0cf6-4588-abec-012afbe1bcd7.png)

**Expected result:** 
There should not be any empty spacing inside the hambergur.

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
