### ISSUE TITLE
CART PAGE( When we add the content then the continue shopping will shift to next line. )  If we align your cart and continue shoppin in middle then it will be much better.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#35]
**Actual result:** 
CART PAGE( When we add the content then the continue shopping will shift to next line. )  If we align your cart and continue shoppin in middle then it will be much better.
![image](https://user-images.githubusercontent.com/102131636/161924240-0d60dcda-1d81-4e09-85c4-babb26a072b8.png)

**Expected result:** 
If we align the Your cart and continue shopping to the next line to one another in new line it will be much better.

**Comment by ui-chandrashekhar** [comment]
No issue
because there is no option for adding text on heading

**Comment by sudhanshu0603** [comment]
ok, resolved
