### ISSUE TITLE
( Cart page ) When we hover over the checkout page then we can give the hover effect for checkout button it will be much better

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#37]
**Actual result:** 
( Cart page ) When we hover over the checkout page then we can give the hover effect for checkout button it will be much better
![image](https://user-images.githubusercontent.com/102131636/161927481-924b5f82-7beb-4512-9ac3-ac3094ccbd8d.png)

**Expected result:**
The hover effect we can give for the checkout button in cart page, it will be much better

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
