### ISSUE TITLE
The newsletter section for the ipad view needs to be improved as the text is not visible properly.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#38]
**Actual result:** 
The newsletter section for the ipad view needs to be improved as the text is not visible properly.
![image](https://user-images.githubusercontent.com/102131636/161932214-44732c46-923e-40e5-b208-fd394a29e736.png)

**Expected results:** 
Text have to be properly visible in the ipad view and the background needs to be improved.

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by sudhanshu0603** [comment]
ok resolved
