### ISSUE TITLE
In collection page when we will apply the filter then the quick view will not work,

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#39]
The url: https://sugarlessbliss.com/collections/all?filter.v.price.gte=&filter.v.price.lte=&sort_by=title-descending
*Actual result:** 
In collection page when we will apply the filter then the quick view will not work,

**Expected result:**
When we use the option of the filter then the quick view have to be clickable and open the modal.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  Issue Resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
