### ISSUE TITLE
Wishlist icon will disappear on applying filter option in search page.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#4]
**The url:** https://107soyodhyqw1pzu-59207385288.shopifypreview.com/search?q=t&options%5Bprefix%5D=last&filter.v.price.gte=&filter.v.price.lte=&sort_by=price-ascending

**Actual result:**
When we will change the filter option then the wishlist icon on the product will disappear.
![image](https://user-images.githubusercontent.com/102131636/161690911-3a91115a-15ff-440c-977a-8c99a12bac01.png)

**Expected result:**
The wishlist should not disppear when we change the filter price low to high.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  Issue resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
