### ISSUE TITLE
collection page double images are coming for mobile view .

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#42]
**The url:** |
https://sugarlessbliss.com/collections/dark-chocolates
**Actual result:**
collection page double images are coming for mobile view .
![image](https://user-images.githubusercontent.com/102131636/162560827-3fc6d985-df72-4186-b90c-78c24fea7150.png)

**Expected result:** 
It must be improved, the url is attached above .

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  Resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
