### ISSUE TITLE
For all the collection the double banners are used. 

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#43]
**The url:**
https://sugarlessbliss.com/collections/oatmeal-creme-cookies
https://sugarlessbliss.com/collections/multigrain-cookies
For all the collection the double collection images are coming.
**Expected result:** 
The collection pages need to be improved.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  Issue with double banne r:resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
