### ISSUE TITLE
Quick view needs to be removed for the mobile view.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#44]
**The url:**  https://sugarlessbliss.com/collections/all
**Actual result:** 
Quick view need to be removed.
**Expected result:** 
The quick view needs to be removed for mobile view as discussed in meeting.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  Quick view removed

**Comment by sudhanshu0603** [comment]
ok, resolved
