### ISSUE TITLE
There must be the continue shopping link in the empty collection product page. 

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#45]
**Actual result:**
There must be the continue shopping link  is not added in the empty collection product page. 
![image](https://user-images.githubusercontent.com/102131636/163125215-d40376f7-c1ae-4818-ad76-a9bc837ace9b.png)

**Expected result:**
There must be the continue shopping link in the empty collection product page. 
-------------------------------------------------------------------------------------------------------------------------------------
**Retesting:**
**Actual result:**
The clear all links are coming. 
![image](https://user-images.githubusercontent.com/102131636/163318032-ae67dfb4-442d-47ab-8dd0-e70091aca1de.png)
**Expected result:**
The reference is attached below, it will be much better.
![image](https://user-images.githubusercontent.com/102131636/163318154-d1522064-5a75-4fea-98bf-092f267c1e80.png)

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by dev-adityapatel** [comment]
![image](https://user-images.githubusercontent.com/100192519/163339251-ab57b275-2e05-4e8d-86a7-e2f0930554e3.png)
@sudhanshu0603   Resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
