### ISSUE TITLE
Search page , the count is coming more and the products counts are coming less.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#46]
**The url:** 
https://sugarlessbliss.com/search?q=m&options%5Bprefix%5D=last
**Actual result:**
Search page , the count is coming more and the products counts are coming less.
![image](https://user-images.githubusercontent.com/102131636/163128832-cf4e5097-01fb-439c-8511-3f49fd910ab2.png)
**Expected result:**
The count have to be as equal as the product are coming.

-----------------------------------------------------------------------------------------------------------------------------------------

**Retesting** 
**The url:**
https://sugarlessbliss.com/search?q=cake&options%5Bprefix%5D=last
**Actual result:**
In search page, the breedcrums the searching count is coming 8 but less product are coming in the screen.
![image](https://user-images.githubusercontent.com/102131636/163317660-9ba3c555-dab9-43de-877e-0eaa9ab2b71a.png)

**Expected result:**
The count have to be same as of the products are coming.

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
