### ISSUE TITLE
we can add some colour for the text link (  addtocart ) , it will be much better. ( suggestion )

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#47]
**Actual result:**
The color for the text add tocart is missing.
https://sugarlessbliss.com/collections/digestive-cookies
**Expected result:**
we can add some colour for the text link (  addtocart ) , it will be much better.( suggestion )

**Comment by ui-chandrashekhar** [comment]
All ready added on hover

**Comment by ui-chandrashekhar** [comment]
All ready added on hover

**Comment by sudhanshu0603** [comment]
ok, resolved
