### ISSUE TITLE
The wihslist icon is coming over the product when we are clicking on the price filter.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#49]
**The url:**
https://sugarlessbliss.com/collections/all
**Actual result:**
The wishlist icon is coming over the product when we are clicking on the price filter.
![image](https://user-images.githubusercontent.com/102131636/163318505-8e579dce-ee71-4728-abdb-f0a3402634ef.png)
**Expected result:** 
The icons of the wishlist should not be visible when clicking on price filter.

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
