### ISSUE TITLE
When we open the sortby and change the price low to high then the wishlist icon is disappearing in collection pages.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#5]
**The url:** https://107soyodhyqw1pzu-59207385288.shopifypreview.com/collections/all?filter.v.price.gte=&filter.v.price.lte=&sort_by=title-descending

**Actual result:**
When we click on the sortby option lowto high price then the wishlist will disappears on all collection pages.
![image](https://user-images.githubusercontent.com/102131636/161691504-be0ea847-19a9-4087-a123-33757508bc6b.png)

**Expected result:**
Wishlist should not disapper only applying filters option.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  Issue resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
