### ISSUE TITLE
The capcha page submit button has some space between button and i am not a robot.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#6]
**Actual result:**
submit button is coming very close to box of i am not a robot.
![image](https://user-images.githubusercontent.com/102131636/161694186-61f5f1fe-6f1e-4cf1-ac6b-7c5c71912cd5.png)

**Expected result:**
There must be some space between the submit button and the box of i am not a robot.

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
