### ISSUE TITLE
Browse by category section on home page below the banner, the speeling of the chocolate is not correct for the category

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Diat-Food-Due-15th-March#9]
Actual result:
The spelling of chocolate is not correct.
![image](https://user-images.githubusercontent.com/102131636/161697380-74db7bfa-daa0-4208-a937-b8cb3fe4f8d0.png)

**Expected result:**
The spelling should be correct.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  Updated

**Comment by sudhanshu0603** [comment]
ok resolved
